### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'dict_values' and 'dict_values'

### ISSUE THREAD

**Issue by MessiLuo** [voladorlu/MARank#2]
您好，很感谢您开源代码，但是运行的时候出了些问题，出现如下所示bug，请问您的project对运行环境有什么要求吗？python和tensorflow分别是啥版本？ 谢谢！
Traceback (most recent call last):
  File "/root/workspace/CTR-master/liukanshan/MARank-master/src/marank.py", line 1072, in <module>
    model = MultiRel(args, userCount, itemCount)
  File "/root/workspace/CTR-master/liukanshan/MARank-master/src/marank.py", line 587, in __init__
    self._init_graph()
  File "/root/workspace/CTR-master/liukanshan/MARank-master/src/marank.py", line 653, in _init_graph
    self.nn_tv = self.weights.values()  + self.biases.values()
TypeError: unsupported operand type(s) for +: 'dict_values' and 'dict_values'

Process finished with exit code 1

**Comment by voladorlu** [comment]
Hi @MessiLuo 非常感谢您的提问，这个代码库用的 tensorflow 是基于 1.8 版本比较旧， python 2.7
